export const gameElements = {
    indice: { xp: 0, prime: 50, image: '/images/Indices/PremierIndice.png' },
    repaire_localise: { xp: 0, prime: 25, image: '/images/exemple.png'  },
    boss_tue: { xp: 0, prime: 25, image: '/images/exemple.png'  },
    contrat_rempli: { xp: 0, prime: 900, image: '/images/exemple.png' },
    bonus_place_nette: { xp: 0, prime: 25, image: '/images/exemple.png' },
    hunterOneStar: { xp: 0, prime: 0, image: '/images/exemple.png'  },
    hunterTwoStar: { xp: 0, prime: 0, image: '/images/exemple.png'  },
    hunterThreeStar: { xp: 350, prime: 0, image: '/images/exemple.png'  },
    hunterFourStar: { xp: 0, prime: 0, image: '/images/exemple.png'  },
    reanimation: { xp: 100, prime: 0, image: '/images/exemple.png'  },
    goule: { xp: 20, prime: 0, image: '/images/exemple.png'  },
    ruche: { xp: 60, prime: 0, image: '/images/exemple.png'  },
    cerbere: { xp: 40, prime: 0, image: '/images/exemple.png'  },
    cuirasse: { xp: 60, prime: 0, image: '/images/exemple.png'  },
    immolateur: { xp: 60, prime: 0, image: '/images/exemple.png'  },
    sac_a_viande: { xp: 60, prime: 0, image: '/images/exemple.png'  },
    sangsue: { xp: 10, prime: 0, image: '/images/exemple.png'  },
};